# Aqui é definido o componente responsável pelo gerenciamento dos controladores no ambiente do ROS
controller_manager:
  ros__parameters:
    update_rate: 30 # Aqui é definido a taxa de atualização para 30 Hz
    use_sim_time: true # Aqui é definido que o tempo a ser utilizado é o tempo da simulação no lugar do tempo real

    diff_cont: # Aqui é criado o controlador do tipo diff_drive_controller, utilizado em robôs de tração diferencial, onde o movimento das rodas é independente
      type: diff_drive_controller/DiffDriveController

    joint_broad: # Aqui é criado o componente, que publica o estado das juntas do robôs
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link # Aqui é definido o quadro de referência para o controlador

    left_wheel_names: ["left_wheel_joint"] # Nome da junta que controla a roda esquerda
    right_wheel_names: ["right_wheel_joint"] # Nome da junta que controla a roda direita
    wheel_separation: 0.35 # Separção entre as rodas
    wheel_radius: 0.05 # Raio das rodas

    use_stamped_vel: false # As velocidades comandadas não precisam de um carimbo de data/hora, ou seja, os comandos de velocidade são tratados como velocidades constantes

    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
# joint_broad:
#   ros__parameters:
